@_exported import JSONSchema
@_exported import JSONSchemaBuilder

// The authoring API. A tool is a `@Schemable @MCPTool` struct whose stored properties are
// its arguments. Types nested in inputs or outputs are `@Schemable @MCPSchema`; closed value
// sets are `@Schemable @MCPEnum`. See docs/architecture.md#typed-tools.

/// Declares a tool. The struct's `///` comment is the tool description; each stored
/// property's `///` comment is that argument's description. Every annotation must be chosen.
@attached(extension, conformances: MCPTool, names: named(metadata), named(describedFields))
public macro MCPTool(
    title: String,
    readOnly: Bool,
    destructive: Bool,
    idempotent: Bool,
    openWorld: Bool,
    name: String? = nil
) = #externalMacro(module: "MCPHostMacrosPlugin", type: "MCPToolMacro")

/// Marks a struct used inside tool inputs or outputs; every property needs a `///` comment.
@attached(extension, conformances: MCPDescribedFields, names: named(describedFields))
public macro MCPSchema() = #externalMacro(module: "MCPHostMacrosPlugin", type: "MCPSchemaMacro")

/// Marks an enum of plain values; every case needs a `///` comment, shown next to its value.
@attached(extension, conformances: MCPDescribedEnum, names: named(caseDescriptions))
public macro MCPEnum() = #externalMacro(module: "MCPHostMacrosPlugin", type: "MCPEnumMacro")

/// A tool: its arguments are the conforming struct, parsed and validated before `call` runs.
///
/// Conform with `@MCPTool`, not by hand. `call` must use typed throws with a ``ToolError``,
/// or `Never` when the tool cannot fail in a way the agent can act on.
public protocol MCPTool: Schemable, MCPDescribedFields, Sendable where Schema.Output == Self {
    associatedtype Output: Schemable & MCPDescribedFields & Encodable & Sendable where Output.Schema.Output == Output
    associatedtype Failure: ToolError

    static var metadata: ToolMetadata { get }

    func call(context: ToolContext) async throws(Failure) -> Output
}

/// Describes the Swift type behind each property, so the library can find nested types and
/// enums when it prepares the schema agents see. Generated by the macros.
public protocol MCPDescribedFields {
    static var describedFields: [DescribedField] { get }
}

public struct DescribedField {
    public let name: String
    public let type: Any.Type

    public init(name: String, type: Any.Type) {
        self.name = name
        self.type = type
    }
}

/// An enum whose cases carry descriptions. Generated by `@MCPEnum`.
public protocol MCPDescribedEnum {
    static var caseDescriptions: [(value: String, description: String)] { get }
}

/// An expected failure the agent can act on. Each case gives a stable code, what happened,
/// and what the agent should do next. See docs/requirements.md#tool-errors.
public protocol ToolError: Error, Sendable {
    /// Stable snake_case identifier, for example `chat_not_found`.
    var code: String { get }
    /// One or two sentences on what went wrong, naming the values involved.
    var message: String { get }
    /// What the agent should do next, for example "Call find_chats and pass its chatID."
    var nextStep: String { get }
    /// Optional structured details.
    var details: JSONValue? { get }
}

extension ToolError {
    public var details: JSONValue? { nil }
}

extension Never: ToolError {
    public var code: String { switch self {} }
    public var message: String { switch self {} }
    public var nextStep: String { switch self {} }
}
