/// A tool's safety hints. All four are required; the spec's defaults are not inherited.
/// See docs/requirements.md#definition.
public struct ToolAnnotations: Sendable, Equatable {
    /// The tool does not change any state.
    public let readOnly: Bool
    /// The tool may make changes that are hard to reverse. Meaningful only when not read-only.
    public let destructive: Bool
    /// Repeating a call with the same arguments has no further effect.
    public let idempotent: Bool
    /// The tool reaches the open internet or arbitrary external entities. A bounded private
    /// account or local store is not open-world.
    public let openWorld: Bool

    public init(readOnly: Bool, destructive: Bool, idempotent: Bool, openWorld: Bool) {
        self.readOnly = readOnly
        self.destructive = destructive
        self.idempotent = idempotent
        self.openWorld = openWorld
    }
}

/// Name, title, description and annotations, generated by `@MCPTool`.
public struct ToolMetadata: Sendable, Equatable {
    public let name: String
    public let title: String
    public let description: String
    public let annotations: ToolAnnotations

    public init(name: String, title: String, description: String, annotations: ToolAnnotations) {
        self.name = name
        self.title = title
        self.description = description
        self.annotations = annotations
    }
}

/// What a handler knows about the request it is serving.
public struct ToolContext: Sendable {
    /// The configured client connection the request arrived through. A label, not authentication.
    public let caller: CallerIdentity
    /// The protocol revision the request is served under.
    public let revision: ProtocolRevision

    public init(caller: CallerIdentity, revision: ProtocolRevision) {
        self.caller = caller
        self.revision = revision
    }
}
